language: rust
cache: cargo
matrix:
  include:
  - rust: stable
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo fmt -- --check
  - cargo clippy -- -D warnings
  - cargo build --verbose
  - cargo test --verbose
