[package]
name = "rustyboy"
version = "0.1.0"
authors = ["Dave Allie <dave@daveallie.com>"]

[features]
default = []
debugger = []
frame-capture = ["image"]

[dependencies]
glium = "0.22"
glutin = "0.17"
image = { version = "*", optional = true }
clippy = { version = "*", optional = true }
